create table if not exists public.bot_runs (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'idle',
  symbol text not null default 'ONDOUSDT',
  interval text not null default '15m',
  buy_strategy integer not null,
  leverage integer not null,
  take_profit_pct numeric not null,
  stop_loss_pct numeric not null,
  last_candle_time timestamptz,
  started_at timestamptz default now(),
  stopped_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.bot_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.bot_runs(id) on delete cascade,
  level text not null default 'info',
  event_type text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.bot_runs enable row level security;
alter table public.bot_events enable row level security;

create table if not exists public.bot_settings (
  id text primary key default 'default',
  enabled boolean not null default true,
  symbol text not null default 'ONDOUSDT',
  interval text not null default '15m',
  buy_strategy integer not null default 1,
  leverage integer not null default 1,
  take_profit_pct numeric not null default 0.2,
  stop_loss_pct numeric not null default 0.2,
  updated_at timestamptz not null default now()
);

insert into public.bot_settings (
  id,
  enabled,
  symbol,
  interval,
  buy_strategy,
  leverage,
  take_profit_pct,
  stop_loss_pct
)
values (
  'default',
  true,
  'ONDOUSDT',
  '15m',
  1,
  1,
  0.2,
  0.2
)
on conflict (id) do nothing;

alter table public.bot_settings enable row level security;
